### PR TITLE
fix: duplicate call loginFunc (#3860)

### LINKED ISSUE #3860: panic: close of closed channel
### Bug Description

```shell
2023-12-19 06:59:25 panic: close of closed channel
2023-12-19 06:59:25 
2023-12-19 06:59:25 goroutine 22 [running]:
2023-12-19 06:59:25 github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess.func1()
2023-12-19 06:59:25     github.com/fatedier/frp/client/service.go:331 +0x498
2023-12-19 06:59:25 github.com/fatedier/frp/pkg/util/wait.BackoffUntil(0x400031de10, {0x862b40, 0x40003502d0}, 0x1, 0x400032ba40)
2023-12-19 06:59:25     github.com/fatedier/frp/pkg/util/wait/backoff.go:135 +0xe0
2023-12-19 06:59:25 github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess(0x40001f21c0, 0x4a817c800, 0x0)
2023-12-19 06:59:25     github.com/fatedier/frp/client/service.go:336 +0x164
2023-12-19 06:59:25 github.com/fatedier/frp/client.(*Service).keepControllerWorking.func1()
2023-12-19 06:59:25     github.com/fatedier/frp/client/service.go:198 +0x34
2023-12-19 06:59:25 github.com/fatedier/frp/pkg/util/wait.BackoffUntil(0x400031df98, {0x862b40, 0x400022d0e0}, 0x1, 0x4000114360)
2023-12-19 06:59:25     github.com/fatedier/frp/pkg/util/wait/backoff.go:135 +0xe0
2023-12-19 06:59:25 github.com/fatedier/frp/client.(*Service).keepControllerWorking(0x40001f21c0)
2023-12-19 06:59:25     github.com/fatedier/frp/client/service.go:195 +0x114
2023-12-19 06:59:25 created by github.com/fatedier/frp/client.(*Service).Run
2023-12-19 06:59:25     github.com/fatedier/frp/client/service.go:173 +0x144
```

### frpc Version

0.53.0

### frps Version

0.53.0

### System Architecture

linux/amd64

### Configurations

N/A

### Logs

_No response_

### Steps to reproduce

I don` know.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

### LINKED ISSUE #3870: 我在容器中运行frpc,当容器停止后,无法再次启动frpc,除非我重启整个系统
### Bug Description

root@17c36744a7be:/data/docker/frpc# ./frpc -c frpc.toml 
2023/12/20 15:05:10 [I] [root.go:141] start frpc service for config file [frpc.toml]
2023/12/20 15:05:10 [I] [service.go:288] try to connect to server...
2023/12/20 15:05:14 [I] [service.go:279] [48de1c586b168eb3] login to server success, get run id [48de1c586b168eb3]
2023/12/20 15:05:14 [I] [proxy_manager.go:173] [48de1c586b168eb3] proxy added: [portal]
2023/12/20 15:05:14 [I] [service.go:288] [48de1c586b168eb3] try to connect to server...
2023/12/20 15:05:14 [I] [control.go:169] [48de1c586b168eb3] [portal] start proxy success
2023/12/20 15:05:19 [I] [service.go:279] [48de1c586b168eb3] login to server success, get run id [48de1c586b168eb3]
2023/12/20 15:05:19 [I] [proxy_manager.go:173] [48de1c586b168eb3] proxy added: [portal]
2023/12/20 15:05:19 [I] [panic.go:884] frpc service for config file [frpc.toml] stopped
panic: close of closed channel

goroutine 1 [running]:
github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess.func1()
	github.com/fatedier/frp/client/service.go:331 +0x517
github.com/fatedier/frp/pkg/util/wait.BackoffUntil(0xc000217a10, {0xd2f4a0, 0xc0000fd710}, 0x1, 0xc0000943c0)
	github.com/fatedier/frp/pkg/util/wait/backoff.go:135 +0x118
github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess(0xc00017c1c0, 0x2540be400, 0x1)
	github.com/fatedier/frp/client/service.go:336 +0x1e9
github.com/fatedier/frp/client.(*Service).Run(0xc00017c1c0, {0xd35450?, 0xc0000a6000?})
	github.com/fatedier/frp/client/service.go:166 +0x10c
github.com/fatedier/frp/cmd/frpc/sub.startService(0xc000158840, {0xc00012dfb0, 0x1, 0x1}, {0x1182358, 0x0, 0x0}, {0x7ffd0071590d, 0x9})
	github.com/fatedier/frp/cmd/frpc/sub/root.go:159 +0x37d
github.com/fatedier/frp/cmd/frpc/sub.runClient({0x7ffd0071590d, 0x9})
	github.com/fatedier/frp/cmd/frpc/sub/root.go:129 +0x19c
github.com/fatedier/frp/cmd/frpc/sub.glob..func2(0x1147100?, {0xb8a06f?, 0x2?, 0x2?})
	github.com/fatedier/frp/cmd/frpc/sub/root.go:69 +0x4c
github.com/spf13/cobra.(*Command).execute(0x1147100, {0xc0000a2160, 0x2, 0x2})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0x1147100)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/fatedier/frp/cmd/frpc/sub.Execute()
	github.com/fatedier/frp/cmd/frpc/sub/root.go:100 +0x25
main.main()

### frpc Version

0.53.0

### frps Version

0.53.0

### System Architecture

linux/amd64

### Configurations

serverAddr = "zchome.us.to"
serverPort = 14443

[[proxies]]
name = "portal"
type = "tcp"
localIP = "nginx"
localPort = 8070
remotePort = 9070

### Logs

root@17c36744a7be:/data/docker/frpc# ./frpc -c frpc.toml 
2023/12/20 15:05:10 [I] [root.go:141] start frpc service for config file [frpc.toml]
2023/12/20 15:05:10 [I] [service.go:288] try to connect to server...
2023/12/20 15:05:14 [I] [service.go:279] [48de1c586b168eb3] login to server success, get run id [48de1c586b168eb3]
2023/12/20 15:05:14 [I] [proxy_manager.go:173] [48de1c586b168eb3] proxy added: [portal]
2023/12/20 15:05:14 [I] [service.go:288] [48de1c586b168eb3] try to connect to server...
2023/12/20 15:05:14 [I] [control.go:169] [48de1c586b168eb3] [portal] start proxy success
2023/12/20 15:05:19 [I] [service.go:279] [48de1c586b168eb3] login to server success, get run id [48de1c586b168eb3]
2023/12/20 15:05:19 [I] [proxy_manager.go:173] [48de1c586b168eb3] proxy added: [portal]
2023/12/20 15:05:19 [I] [panic.go:884] frpc service for config file [frpc.toml] stopped
panic: close of closed channel

goroutine 1 [running]:
github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess.func1()
	github.com/fatedier/frp/client/service.go:331 +0x517
github.com/fatedier/frp/pkg/util/wait.BackoffUntil(0xc000217a10, {0xd2f4a0, 0xc0000fd710}, 0x1, 0xc0000943c0)
	github.com/fatedier/frp/pkg/util/wait/backoff.go:135 +0x118
github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess(0xc00017c1c0, 0x2540be400, 0x1)
	github.com/fatedier/frp/client/service.go:336 +0x1e9
github.com/fatedier/frp/client.(*Service).Run(0xc00017c1c0, {0xd35450?, 0xc0000a6000?})
	github.com/fatedier/frp/client/service.go:166 +0x10c
github.com/fatedier/frp/cmd/frpc/sub.startService(0xc000158840, {0xc00012dfb0, 0x1, 0x1}, {0x1182358, 0x0, 0x0}, {0x7ffd0071590d, 0x9})
	github.com/fatedier/frp/cmd/frpc/sub/root.go:159 +0x37d
github.com/fatedier/frp/cmd/frpc/sub.runClient({0x7ffd0071590d, 0x9})
	github.com/fatedier/frp/cmd/frpc/sub/root.go:129 +0x19c
github.com/fatedier/frp/cmd/frpc/sub.glob..func2(0x1147100?, {0xb8a06f?, 0x2?, 0x2?})
	github.com/fatedier/frp/cmd/frpc/sub/root.go:69 +0x4c
github.com/spf13/cobra.(*Command).execute(0x1147100, {0xc0000a2160, 0x2, 0x2})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0x1147100)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/fatedier/frp/cmd/frpc/sub.Execute()
	github.com/fatedier/frp/cmd/frpc/sub/root.go:100 +0x25
main.main()

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

### LINKED ISSUE #3876: failed after connect success on linux/arm64
### Bug Description

failed after connect success on linux/arm64

### frpc Version

0.53.0

### frps Version

0.53.0

### System Architecture

linux/arm64

### Configurations

```json
{
  "serverAddr": "frp.server",
  "serverPort": 7000,
    "auth": {
      "method": "token",
      "token": "token"
    },
    "proxies": [{
      "name": "jhit-deepin",
      "type": "tcp",
      "localIP": "127.0.0.1",
      "localPort": 22,
      "remotePort": 50022
    }]
}

```

### Logs

```
/etc/frp$ sudo ./frpc -c frpc.json

2023/12/21 19:02:10 [I] [root.go:141] start frpc service for config file [frpc.json]
2023/12/21 19:02:10 [I] [service.go:288] try to connect to server...
2023/12/21 19:02:15 [I] [service.go:279] [d70a69d35a2e3cf8] login to server success, get run id [d70a69d35a2e3cf8]
2023/12/21 19:02:15 [I] [proxy_manager.go:173] [d70a69d35a2e3cf8] proxy added: [jhit-deepin]
2023/12/21 19:02:15 [I] [service.go:288] [d70a69d35a2e3cf8] try to connect to server...
2023/12/21 19:02:16 [I] [control.go:169] [d70a69d35a2e3cf8] [jhit-deepin] start proxy success
2023/12/21 19:02:21 [I] [service.go:279] [d70a69d35a2e3cf8] login to server success, get run id [d70a69d35a2e3cf8]
2023/12/21 19:02:21 [I] [proxy_manager.go:173] [d70a69d35a2e3cf8] proxy added: [jhit-deepin]
2023/12/21 19:02:21 [I] [panic.go:884] frpc service for config file [frpc.json] stopped
panic: close of closed channel

goroutine 1 [running]:
github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess.func1()
        github.com/fatedier/frp/client/service.go:331 +0x498
github.com/fatedier/frp/pkg/util/wait.BackoffUntil(0x40001f99e0, {0x862b40, 0x40000e9710}, 0x1, 0x4000098420)
        github.com/fatedier/frp/pkg/util/wait/backoff.go:135 +0xe0
github.com/fatedier/frp/client.(*Service).loopLoginUntilSuccess(0x4000032460, 0x2540be400, 0x1)
        github.com/fatedier/frp/client/service.go:336 +0x164
github.com/fatedier/frp/client.(*Service).Run(0x4000032460, {0x868a10?, 0x40000340e0?})
        github.com/fatedier/frp/client/service.go:166 +0xf8
github.com/fatedier/frp/cmd/frpc/sub.startService(0x40001b8840, {0x4000189cf0, 0x1, 0x1}, {0xc99300, 0x0, 0x0}, {0xfffff4ffe47f, 0x9})
        github.com/fatedier/frp/cmd/frpc/sub/root.go:159 +0x2a0
github.com/fatedier/frp/cmd/frpc/sub.runClient({0xfffff4ffe47f, 0x9})
        github.com/fatedier/frp/cmd/frpc/sub/root.go:129 +0x138
github.com/fatedier/frp/cmd/frpc/sub.glob..func2(0xc57fc0?, {0x6be840?, 0x2?, 0x2?})
        github.com/fatedier/frp/cmd/frpc/sub/root.go:69 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc57fc0, {0x4000030190, 0x2, 0x2})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0x7b0
github.com/spf13/cobra.(*Command).ExecuteC(0xc57fc0)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x364
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/fatedier/frp/cmd/frpc/sub.Execute()
        github.com/fatedier/frp/cmd/frpc/sub/root.go:100 +0x24
main.main()
        github.com/fatedier/frp/cmd/frpc/main.go:23 +0x1c
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

### PR DESCRIPTION
**Pull request by im-zhou**
### WHY
modify ext func, specify whether exit immediately

Fix #3860 
Fix #3870 
Fix #3876

### CODE REVIEW

File: client/service.go [hunk 1]
```diff
@@ -284,15 +284,15 @@ func (svr *Service) loopLoginUntilSuccess(maxInterval time.Duration, firstLoginE
 	xl := xlog.FromContextSafe(svr.ctx)
 	successCh := make(chan struct{})
 
-	loginFunc := func() error {
+	loginFunc := func() (done bool, err error) {
```
Comment (fatedier) [inline client/service.go:287]: done 和 err 一般不用先定义出来，直接返回就好了。`loginFunc := func() (bool, error) {`

Comment (im-zhou) [reply client/service.go]: 已修改

File: client/service.go [hunk 2]
```diff
@@ -284,15 +284,15 @@ func (svr *Service) loopLoginUntilSuccess(maxInterval time.Duration, firstLoginE
 	xl := xlog.FromContextSafe(svr.ctx)
 	successCh := make(chan struct{})
```
Comment (fatedier) [inline client/service.go:285]: After the mechanism is modified, this channel is no longer needed.

Comment (im-zhou) [reply client/service.go]: 看起来 `MergeAndCloseOnAnyStopChannel` 也不再需要了

**Review by fatedier — APPROVED** [review]
